---
version: '2'
catalog:
    name: "Starterkit"
    version: "v1.0"
    description: "Starterkit deployment"
    uuid: starterkit-0
    minimum_rancher_version: 'v1.6'

questions:
    -   variable: "ALLOWED_HOSTS"
        label: "List of allowed host header values"
        description: |
            List of host header values which should be
            permitted. You should add full-qualified domain
            names under which deployment is visible. Default
            values, django and geonode values are
            added internally. Example ['123.123.123.123','foo.bar.org']
        required: true
        type: string
        default: "['django',]"

    -   variable: "HOST_AFFINITY"
        label: "Label of host to deploy on"
        description: |
            To keep containers running on specific
            hosts, provide label attached to host
            to deploy on. For example, if you create a label
            when deploying your host with key geonode
            and value true then you would enter here geonode=true
        required: true
        type: string
        default:
services:
    db:
        scale: 1
        labels:
            io.rancher.scheduler.affinity:host_label: ${HOST_AFFINITY}
    dbsos:
        scale: 1
        labels:
            io.rancher.scheduler.affinity:host_label: ${HOST_AFFINITY}
    elasticsearch:
        scale: 1
        labels:
            io.rancher.scheduler.affinity:host_label: ${HOST_AFFINITY}
    rabbitmq:
        scale: 1
        labels:
            io.rancher.scheduler.affinity:host_label: ${HOST_AFFINITY}
    django:
        # retain_ip: true
        scale: 1
        labels:
            io.rancher.scheduler.affinity:host_label: ${HOST_AFFINITY}
    celery:
        # retain_ip: true
        scale: 1
        labels:
            io.rancher.scheduler.affinity:host_label: ${HOST_AFFINITY}
    geoserver:
        scale: 1
        labels:
            io.rancher.scheduler.affinity:host_label: ${HOST_AFFINITY}
    consumers:
        # retain_ip: true
        scale: 1
        labels:
            io.rancher.scheduler.affinity:host_label: ${HOST_AFFINITY}
    sos:
        scale: 1
        labels:
            io.rancher.scheduler.affinity:host_label: ${HOST_AFFINITY}
    geonode:
        scale: 1
        labels:
            io.rancher.scheduler.affinity:host_label: ${HOST_AFFINITY}
    data-dir-conf:
        labels:
            io.rancher.container.start_once: true
            io.rancher.scheduler.affinity:host_label: ${HOST_AFFINITY}
        scale: 1